site_name: SEED Platform&trade; Documentation

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: 'images/icon-city.svg'  
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'en'
  favicon: 'images/favicon.ico'
  # feature:
  #   tabs: true

extra_css:
  - 'stylesheets/extra.css'

nav:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - FAQ: 'faq.md'
  - User Documentation: 'documentation.md'
  - Developer Documentation: 'developer_resources.md'
  - Known Issues: 'known_issues.md'
  - References: 'references.md'
  - SEED Technical Allies: 'technical_ally.md'

  
